server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: dGVzdGVTZWNyZXRLZXlTbWFydEd5bTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2
  expiration: 86400000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: seuemail@gmail.com
    password: sua-senha-de-app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin

  datasource:
    url: jdbc:postgresql://localhost:5433/smartgym_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    error:
      include-stacktrace: never
      include-message: always
      whitelabel:
        enabled: false

app:
  seed:
    enabled: true
