server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  profiles:
    active: local

  security:
    user:
      name: admin

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: ""
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  web:
    error:
      include-stacktrace: never
      include-message: always
      whitelabel:
        enabled: false

app:
  seed:
    enabled: true
  mqtt:
    url: tcp://localhost:1883
    client-id: smartgym-backend
    username: ""
    password: ""
    topic:
      telemetry: smartgym/device/+/telemetry
      command-prefix: smartgym/device
