jwt:
  secret: dGVzdGVTZWNyZXRLZXlTbWFydEd5bTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2

spring:
  mail:
    username: equipesmartgym@gmail.com
    password: cgcrjtxcnykjjevb

  security:
    user:
      name: admin

  datasource:
    url: jdbc:postgresql://localhost:5433/smartgym_db
    username: admin
    password: admin